parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Repository\AnswerRepository:
        arguments:
            $entityClass: 'App\Entity\Answer'

    App\Repository\DialogRepository:
        arguments:
            $entityClass: 'App\Entity\Dialog'

    App\Repository\MainCharacterRepository:
        arguments:
            $entityClass: 'App\Entity\MainCharacter'

    App\Repository\FamilyMemberRepository:
        arguments:
            $entityClass: 'App\Entity\FamilyMember'

    App\Form\FamilyMemberType:
        autowire: true
        arguments:
            $uploadDir: '%kernel.project_dir%/public/uploads/images/'